# Pre-commit hooks for SQL quality
repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.3.5
    hooks:
      - id: sqlfluff-lint
        args: [--dialect=postgres]
        additional_dependencies: ['dbt-postgres', 'sqlfluff-templater-dbt']
      - id: sqlfluff-fix
        args: [--dialect=postgres]
        additional_dependencies: ['dbt-postgres', 'sqlfluff-templater-dbt']
        
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        types: [sql]
      - id: end-of-file-fixer
        types: [sql]
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      
  - repo: local
    hooks:
      - id: sql-check-business-logic
        name: Check SQL Business Logic
        entry: python scripts/check_sql_business_logic.py
        language: python
        types: [sql]
        require_serial: true
        additional_dependencies: [sqlparse]
